# Generated by Django 3.2 on 2023-02-23 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_article_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='meta_des',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='article',
            name='meta_keywords',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
    ]
